version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: dockerfile
    container_name: ecommerce-backend
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/app # Cập nhật đường dẫn volumes
      - /app/node_modules
    env_file:
      - ./backend/.env # Cập nhật đường dẫn file .env
    networks:
      - ecommerce-network
    depends_on:
      - mongo
      - kafka
      - zookeeper
  spark:
    build:
      context: ./model
    container_name: spark-processor
    volumes:
      - ./model:/app
    depends_on:
      - mongo
      - kafka
    networks:
      - ecommerce-network
    command:
      - "/opt/spark/bin/spark-submit"
      - "--packages"
      - "org.apache.spark:spark-sql-kafka-0-10_2.12:3.3.0,org.mongodb.spark:mongo-spark-connector_2.12:3.0.1"
      - "/app/spark_processor.py"

  mongo:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - ecommerce-network

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    restart: always
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: |
        PLAINTEXT://kafka:9092,
        PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: |
        PLAINTEXT:PLAINTEXT,
        PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - ecommerce-network

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - ecommerce-network


volumes:
  mongo_data:

networks:
  ecommerce-network:
    driver: bridge