# base image
FROM node:16

# install curl và netcat
RUN apt-get update && apt-get install -y curl netcat

# set working directory
WORKDIR /app

# copy package files
COPY package*.json ./

# install dependencies
RUN npm install

# copy app files
COPY . .

# copy wait-for.sh and set permission
COPY wait-for.sh /wait-for.sh
RUN chmod +x /wait-for.sh

# expose app port
EXPOSE 4000

# start app only after kafka is ready
CMD ["/wait-for.sh", "kafka:9092", "--", "npm", "start"]
