version: '3.8'

services:
  backend:
    container_name: ecommerce-backend
    build: .
    ports:
      - "4000:4000"
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
    depends_on:
      - mongo
      - redis
    networks:
      - ecommerce-network


  mongo:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - ecommerce-network


  redis:
    image: redis
    container_name: redis-backend
    ports:
      - "6380:6379"
    networks:
      - ecommerce-network

volumes:
  mongo_data:

networks:
  ecommerce-network: